# Generated by Django 6.0.3 on 2026-05-18 12:00

import django.core.validators
from django.db import migrations, models

import leads.models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('location', models.CharField(max_length=120)),
                ('college', models.CharField(max_length=160)),
                (
                    'resume',
                    models.FileField(
                        upload_to=leads.models.career_resume_upload_path,
                        validators=[django.core.validators.FileExtensionValidator(['pdf'])],
                    ),
                ),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('NEW', 'New'),
                            ('HOLD', 'Hold'),
                            ('ACCEPTED', 'Accepted'),
                            ('REJECTED', 'Rejected'),
                        ],
                        default='NEW',
                        max_length=12,
                    ),
                ),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
