# Generated by Django 4.2.30 on 2026-05-18 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_careerapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='careerapplication',
            name='role',
            field=models.CharField(choices=[('Wealth Analyst', 'Wealth Analyst'), ('Relationship Manager', 'Relationship Manager'), ('Operations Executive', 'Operations Executive'), ('Other', 'Other')], default='Wealth Analyst', max_length=50),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='careerapplication',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
