# Generated by Django on 2026-05-18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_careerapplication_role_alter_appointment_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('COMPLETED', 'Completed'), ('CANCELED', 'Canceled')], default='NEW', max_length=12),
        ),
        migrations.AddField(
            model_name='appointment',
            name='note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
