# Generated by Django 4.2.30 on 2026-05-18 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0004_appointment_management_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('job_description', models.TextField(help_text='Complete job description (mandatory)')),
                ('requirements', models.TextField(blank=True, help_text='Technical and soft skills requirements')),
                ('responsibilities', models.TextField(blank=True, help_text='Key responsibilities')),
                ('benefits', models.TextField(blank=True, help_text='Benefits and perks')),
                ('is_active', models.BooleanField(default=True, help_text="If unchecked, this role won't appear on careers page")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='careerapplication',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='careerapplication',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='leads.role'),
        ),
    ]
