# Generated by Django 4.2.30 on 2026-05-18 12:45

from django.db import migrations


def create_initial_roles(apps, schema_editor):
    """Create initial role objects from the hardcoded list"""
    Role = apps.get_model('leads', 'Role')
    
    roles_data = [
        {
            'name': 'Wealth Analyst',
            'job_description': 'Support portfolio reviews, goal planning, and client reporting.',
            'responsibilities': 'Goal mapping\nResearch notes\nReview packs',
        },
        {
            'name': 'Relationship Manager',
            'job_description': 'Own the client journey and ensure timely follow-ups and updates.',
            'responsibilities': 'Onboarding\nReview cadence\nIssue resolution',
        },
        {
            'name': 'Operations Executive',
            'job_description': 'Keep documentation, compliance, and process execution precise.',
            'responsibilities': 'Compliance logs\nBack-office sync\nReporting cadence',
        },
    ]
    
    for role_data in roles_data:
        Role.objects.get_or_create(
            name=role_data['name'],
            defaults={
                'job_description': role_data['job_description'],
                'responsibilities': role_data['responsibilities'],
                'is_active': True,
            }
        )


def migrate_existing_applications(apps, schema_editor):
    """Migrate existing CareerApplication objects to use Role ForeignKey"""
    CareerApplication = apps.get_model('leads', 'CareerApplication')
    Role = apps.get_model('leads', 'Role')
    
    # Map old string role values to new Role objects
    role_mapping = {
        'Wealth Analyst': 'Wealth Analyst',
        'Relationship Manager': 'Relationship Manager',
        'Operations Executive': 'Operations Executive',
        'Other': 'Wealth Analyst',  # Default to Wealth Analyst if 'Other'
    }
    
    # Get all applications and update them
    for app in CareerApplication.objects.all():
        if app.role_id is None:  # Only process if role is not set yet
            # Try to find matching role
            old_role_name = getattr(app, '_old_role', None)
            if old_role_name and old_role_name in role_mapping:
                new_role_name = role_mapping[old_role_name]
                try:
                    role = Role.objects.get(name=new_role_name)
                    app.role = role
                    app.save(update_fields=['role'])
                except Role.DoesNotExist:
                    # If role doesn't exist, use first available role
                    role = Role.objects.first()
                    if role:
                        app.role = role
                        app.save(update_fields=['role'])


def reverse_migrate(apps, schema_editor):
    """Reverse migration - delete created roles if needed"""
    Role = apps.get_model('leads', 'Role')
    Role.objects.filter(name__in=['Wealth Analyst', 'Relationship Manager', 'Operations Executive']).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0005_role_alter_careerapplication_options_and_more'),
    ]

    operations = [
        migrations.RunPython(create_initial_roles, reverse_migrate),
        migrations.RunPython(migrate_existing_applications),
    ]
