# Generated by Django 4.2.30 on 2026-06-15 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0006_populate_initial_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='service',
            field=models.CharField(choices=[('WEALTH', 'Goal based Wealth creation solutions'), ('TERM', 'Term Insurance'), ('HEALTH', 'Health Insurance'), ('LOANS', 'Loans & Credit Solutions')], max_length=50),
        ),
    ]
