# Generated by Django 4.2.16 on 2026-06-23 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0007_alter_appointment_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='service',
            field=models.CharField(choices=[('WEALTH', 'Goal based Wealth creation solutions'), ('TERM', 'Term Insurance'), ('HEALTH', 'Health Insurance'), ('LOANS', 'Loans & Credit Solutions'), ('LEGACY', 'Legacy Planning')], max_length=50),
        ),
    ]
